name: remarkable
version: git
summary: Remarkable editor
description: |
   A free fully featured markdown editor for Linux.
confinement: strict
base: core18
grade: stable

parts:
  add-sources:
    plugin: dump
    source: .
    override-prime: |
      sed -i -e 's/Icon=remarkable/Icon=${SNAP}\/data\/media\/remarkable.png/' /root/stage/remarkable.desktop
      sed -i -e 's/Popen(sys.argv\[0\])/Popen(\[sys.executable, sys.argv\[0\]\])/' /root/stage/remarkable/RemarkableWindow.py
      sed -i -e 's/Popen(\[sys.argv\[0\]/Popen(\[sys.executable, sys.argv\[0\]/' /root/stage/remarkable/RemarkableWindow.py
      snapcraftctl prime
  remarkable:
    after: [desktop-qt5]
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - wkhtmltopdf
      - python3-gi
      - python3-bs4
      - python3-markdown
      - libqt5webkit5
      - libqt5qml5
      - libqt5quick5
      - libqt5sensors5
      - libqt5webchannel5
      - libqt5positioning5
      - gir1.2-webkit2-4.0
      - gir1.2-gtksource-3.0
      - python3-gtkspellcheck

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - libgtk2.0-0
apps:
  remarkable:
    adapter: full
    command: usr/bin/python3 $SNAP/bin/remarkable
    command-chain:
      - bin/desktop-launch
    environment:
      PYTHONPATH: $SNAP/remarkable:$SNAP/remarkable_lib
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/usr/lib:$PATH
      LD_LIBRARY_PATH: $SNAP/usr/lib:$LD_LIBRARY_PATH
    extensions: [gnome-3-28]
    desktop: remarkable.desktop
    plugs:
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - unity7
      - removable-media

