name: remarkable
version: git
summary: Remarkable editor
description: |
   A free fully featured markdown editor for Linux.
confinement: strict
base: core18
grade: stable

parts:
  add-sources:
    plugin: dump
    source: .
    override-prime: |
      sed -i -e 's/Icon=remarkable/Icon=${SNAP}\/data\/media\/remarkable.png/' /root/stage/remarkable.desktop
      sed -i -e 's/Popen(sys.argv\[0\])/Popen(\[sys.executable, sys.argv\[0\]\])/' /root/stage/remarkable/RemarkableWindow.py
      sed -i -e 's/Popen(\[sys.argv\[0\]/Popen(\[sys.executable, sys.argv\[0\]/' /root/stage/remarkable/RemarkableWindow.py
      snapcraftctl prime
  remarkable:
    plugin: python
    python-version: python3
    source: .
    build-packages:
      - build-essential
    stage-packages:
      - wkhtmltopdf
      - python3-gi
      - python3-bs4
      - python3-markdown
      - libqt5webkit5
      - libqt5qml5
      - libqt5quick5
      - libqt5sensors5
      - libqt5webchannel5
      - libqt5positioning5
      - gir1.2-webkit2-4.0
      - gir1.2-gtksource-3.0
      - python3-gtkspellcheck
apps:
  remarkable:
    command: usr/bin/python3 $SNAP/bin/remarkable
    environment:
      PYTHONPATH: $SNAP/remarkable:$SNAP/remarkable_lib
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$SNAP/usr/lib:$PATH
      LD_LIBRARY_PATH: $SNAP/usr/lib:$LD_LIBRARY_PATH
    extensions: [gnome-3-28]
    desktop: remarkable.desktop
    plugs:
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - unity7
      - removable-media

